# Python Bing Wallpaper Fetcher Setting Tag

MARKETS='markets'
BING_URL='bing-url'
URL_PARM_FORMAT='url-parm-format'
URL_PARM_INDEX='url-parm-index'
URL_PARM_N='url-parm-n'
XML_BASE_URL='xml-base-url'
WALLPAPER_BASE_URL='wallpaper-base-url'
WALLPAPER_FOLDER='wallpaper-folder'
WALLPAPER_PIXEL_WIDTH='wallpaper-pixel-width'
WALLPAPER_PIXEL_HIGHT='wallpaper-pixel-hight'
WALLPAPER_FORAMT='wallpaper-foramt'
XML_TAG_NAME_IMAGE='xml-tag-name-image'
XML_TAG_NAME_BASE_URL='xml-tag-name-base-url'
XML_TAG_NAME_START_DATE='xml-tag-name-start-date'
XML_PATH_BASE_URL='xml-path-base-url'
XML_PATH_START_DATE='xml-path-start-date'
LOG_FORMAT='log-format'
LOG_FILE_NAME='log-file-name'
FAILURE_SLEEP_TIME='failure-sleep-time'
INIT_DATABASE='init-database'